import type { DraftStore, Interest, OfferRecord, OfferType, Order, PartnerId, PartnerProfile } from "./types";

export const partnerProfiles: Record<PartnerId, PartnerProfile> = {
  petpooja: {
    id: "petpooja",
    name: "PetPooja",
    legalName: "PetPooja Pvt Ltd",
    role: "Admin",
    initials: "P",
    availableOfferTypes: ["direct-buy", "lead-gen"],
  },
  hdfc: {
    id: "hdfc",
    name: "HDFC Bank",
    legalName: "HDFC Bank Limited",
    role: "Partnerships",
    initials: "H",
    availableOfferTypes: ["financial", "linked"],
  },
};

export const offerTypeMeta: Record<OfferType, { title: string; eyebrow: string; description: string; goodFor: string }> = {
  "lead-gen": { title: "Lead generation", eyebrow: "No payment", description: "Merchant fills a form, you follow up offline.", goodFor: "Trials, demos and assisted subscriptions" },
  "direct-buy": { title: "Direct Buy", eyebrow: "Pay via Pine", description: "Merchant pays via Pine, you deliver.", goodFor: "Software licences, hardware and SaaS" },
  financial: { title: "Financial application", eyebrow: "Bank / NBFC", description: "Merchant applies, your team runs KYC and decides.", goodFor: "Loans, cards, accounts and insurance" },
  linked: { title: "Linked bundle", eyebrow: "Bank only", description: "One application covers an account and a device.", goodFor: "Account + POS and multi-leg products" },
};

const common = {
  productMark: "",
  activationMode: "webhook" as const,
  webhookUrl: "https://api.petpooja.in/pine/activation",
  activationSla: "4",
  regulatedEntity: "",
  licence: "",
  cin: "",
  productFamily: "",
  interestRange: "",
  creditCeiling: "",
  disclosures: "",
  dpdpConsent: false,
  mitcFile: "",
  complianceSignoff: false,
  postTrialPrice: "",
  contactSla: "",
  deviceSku: "",
  devicePrice: "",
  inventory: "",
  deviceFulfilment: "",
  activationGate: "both" as const,
};

export const initialDrafts: DraftStore = {
  petpooja: {
    "direct-buy": {
      ...common,
      id: "draft-pet-direct",
      partnerId: "petpooja",
      type: "direct-buy",
      offerName: "Petpooja POS — Annual",
      category: "Billing & POS",
      headline: "1-year Restaurant POS subscription",
      benefit: "Billing, KOT, inventory, analytics — all in one",
      productDescription: "Full-stack restaurant management for growing food businesses.",
      sku: "PP-POS-ANN-2026",
      price: "9999",
      fulfilment: "Digital · SaaS subscription (1 year)",
      heroCreative: "petpooja_hero_1440x810.png",
      validFrom: "2026-10-01",
      validUntil: "2027-09-30",
      terms: "Annual subscription includes onboarding, software updates and standard support. Cancellation and refund terms apply as per the partner policy.",
      questions: [],
    },
    "lead-gen": {
      ...common,
      id: "draft-pet-lead",
      partnerId: "petpooja",
      type: "lead-gen",
      offerName: "3-month free trial · Restaurant POS",
      category: "Billing & POS",
      headline: "3 months free · Restaurant POS software",
      benefit: "Full features · No card required · Cancel anytime",
      productDescription: "Full-stack restaurant management: billing, KOT, inventory, aggregator integrations and GST-ready reports.",
      sku: "PP-POS-TRIAL-2026",
      price: "",
      fulfilment: "Partner follow-up",
      postTrialPrice: "₹1,299/mo",
      contactSla: "48",
      heroCreative: "petpooja_trial_1440x810.png",
      validFrom: "2026-09-15",
      validUntil: "2026-12-15",
      terms: "Trial terms, cancellation policy and data-handling commitments apply.",
      questions: [
        { id: "q-turnover", label: "Monthly turnover", type: "single-select", required: false, options: ["Below ₹5L", "₹5L–₹25L", "₹25L–₹1Cr", "Above ₹1Cr"] },
        { id: "q-timing", label: "How soon are you looking to adopt?", type: "single-select", required: true, options: ["Immediately", "Within 30 days", "Just exploring"] },
      ],
    },
  },
  hdfc: {
    financial: {
      ...common,
      id: "draft-hdfc-financial",
      partnerId: "hdfc",
      type: "financial",
      offerName: "HDFC Business Line — Pre-approved",
      category: "Financial services · Credit",
      headline: "Pre-approved business loan up to ₹15L",
      benefit: "Interest from 12% p.a. · Decision in 24–72 hrs",
      productDescription: "A flexible business line of credit for working capital and growth.",
      sku: "HDFC-BIZLINE-PRE",
      price: "",
      fulfilment: "Application · HDFC underwriting",
      regulatedEntity: "HDFC Bank Limited",
      licence: "RBI licence · Scheduled commercial bank",
      cin: "L65920MH1994PLC080618",
      productFamily: "Business line of credit",
      interestRange: "12% – 18%",
      creditCeiling: "1500000",
      disclosures: "APR, processing fee, penalty on default, cooling-off period and grievance officer contact.",
      dpdpConsent: true,
      mitcFile: "hdfc_business_line_mitc.pdf",
      complianceSignoff: true,
      heroCreative: "hdfc_bizloan_1440x810.png",
      validFrom: "2026-10-01",
      validUntil: "2027-03-31",
      terms: "Platform terms, DPDP consent and the HDFC Bank MITC apply.",
      questions: [
        { id: "q-amount", label: "Requested credit amount", type: "short-text", required: true, options: [] },
        { id: "q-use", label: "Primary use of funds", type: "single-select", required: true, options: ["Working capital", "Equipment", "Expansion", "Other"] },
      ],
    },
    linked: {
      ...common,
      id: "draft-hdfc-linked",
      partnerId: "hdfc",
      type: "linked",
      offerName: "POS terminal + HDFC Business Line",
      category: "Hardware · Financial services",
      headline: "Get a POS terminal + credit line up to ₹10L",
      benefit: "One commitment · device + credit line",
      productDescription: "A Pine POS terminal bundled with an HDFC Business Line application.",
      sku: "HDFC-BUNDLE-2026",
      price: "4999",
      fulfilment: "Two-leg bundle",
      regulatedEntity: "HDFC Bank Limited",
      licence: "RBI licence · Scheduled commercial bank",
      cin: "L65920MH1994PLC080618",
      interestRange: "12% – 18%",
      creditCeiling: "1000000",
      disclosures: "APR, processing fee, penalty, cooling-off period and grievance contact.",
      dpdpConsent: true,
      mitcFile: "hdfc_bundle_mitc.pdf",
      complianceSignoff: true,
      deviceSku: "POS-NKD-2P-STD",
      devicePrice: "4999",
      inventory: "1200",
      deviceFulfilment: "Physical · 3–5 days",
      activationGate: "both",
      heroCreative: "hdfc_pos_bundle_1440x810.png",
      validFrom: "2026-10-01",
      validUntil: "2027-03-31",
      terms: "Platform, order, bundle, DPDP consent and HDFC Bank product terms apply.",
      questions: [
        { id: "q-city", label: "Preferred installation city", type: "short-text", required: true, options: [] },
        { id: "q-purpose", label: "Primary credit-line use", type: "single-select", required: true, options: ["Working capital", "Expansion", "Inventory", "Other"] },
      ],
    },
  },
};

export const initialOffers: OfferRecord[] = [
  { id: "offer-rejected", partnerId: "petpooja", draftType: "lead-gen", name: "Inventory Software — Diwali", meta: "Reason: T&Cs missing cap — click to fix", typeLabel: "Lead-gen", category: "Inventory management", deal: "₹2,000 off annual", interests: null, activated: null, status: "Rejected" },
  { id: "offer-live", partnerId: "petpooja", draftType: "lead-gen", name: "PetPooja CRM — First Year", meta: "Ends in 2 days · 18 open interests", typeLabel: "Lead-gen", category: "Loyalty & CRM", deal: "First year 50% off", interests: 30, activated: 20, status: "Live" },
  { id: "offer-review", partnerId: "petpooja", draftType: "lead-gen", name: "GST Filing Bundle", meta: "Under review 52 hrs · longer than usual", typeLabel: "Lead-gen", category: "Compliance & accounting", deal: "Bundle + support", interests: null, activated: null, status: "Under review" },
  { id: "offer-paused", partnerId: "petpooja", draftType: "direct-buy", name: "Restaurant POS", meta: "Live since 20 Aug · paused 07 Sep", typeLabel: "Direct Buy", category: "Billing & POS", deal: "Free setup + 3 months", interests: 11, activated: 9, status: "Paused" },
  { id: "offer-ended", partnerId: "petpooja", draftType: "direct-buy", name: "Kitchen Display System", meta: "Ended 31 Aug", typeLabel: "Direct Buy", category: "Billing & POS", deal: "Bundle discount", interests: 78, activated: 62, status: "Ended" },
  { id: "hdfc-fin-live", partnerId: "hdfc", draftType: "financial", name: "HDFC Business Line", meta: "Live since 03 Sep", typeLabel: "Financial application", category: "Financial services · Credit", deal: "Credit line up to ₹15L", interests: 84, activated: 26, status: "Live" },
  { id: "hdfc-linked-review", partnerId: "hdfc", draftType: "linked", name: "POS + Business Line", meta: "Submitted yesterday", typeLabel: "Linked bundle", category: "Hardware · Financial services", deal: "Device + credit line", interests: null, activated: null, status: "Under review" },
];

export const initialOrders: Order[] = [
  { id: "ord_8XKAP42Q", partnerId: "petpooja", merchant: "Cafe Mocha Andheri", contactName: "Rahul Shah", email: "rahul@cafemocha.in", gstin: "27AABCU9603R1ZM", consentAt: "24 Sep 2026, 11:02 AM", offer: "POS Annual", placed: "2 hrs ago", status: "Order received", settlement: "Held", amount: "₹9,999", endpoint: "https://api.petpooja.in/pine/activation", deliveryResult: "24 Sep, 11:03 AM · 200 OK" },
  { id: "ord_8XKAP41J", partnerId: "petpooja", merchant: "Momo Point Koramangala", contactName: "Maya Rao", email: "maya@momopoint.in", gstin: "29AACCM4422P1Z8", consentAt: "24 Sep 2026, 7:28 AM", offer: "POS Annual", placed: "6 hrs ago", status: "Installation scheduled", settlement: "Held", amount: "₹9,999", endpoint: "https://api.petpooja.in/pine/activation", deliveryResult: "24 Sep, 7:30 AM · 200 OK" },
  { id: "ord_8XKAP40D", partnerId: "petpooja", merchant: "Anand Bhavan", contactName: "Karthik Iyer", email: "karthik@anandbhavan.in", gstin: "33AAECA1102D1ZP", consentAt: "23 Sep 2026, 2:10 PM", offer: "POS Annual", placed: "Yesterday", status: "Merchant live", settlement: "Released", amount: "₹9,999", endpoint: "https://api.petpooja.in/pine/activation", deliveryResult: "23 Sep, 4:42 PM · activated" },
  { id: "ord_8XKAP3YT", partnerId: "petpooja", merchant: "Delhi Darbar", contactName: "Fahad Khan", email: "fahad@delhidarbar.in", gstin: "07AAHFD2204N1Z5", consentAt: "22 Sep 2026, 10:15 AM", offer: "Monthly Trial", placed: "2 days ago", status: "Declined", settlement: "—", amount: "₹499", endpoint: "https://api.petpooja.in/pine/activation", deliveryResult: "Payment failed before delivery", refund: { reason: "Duplicate debit reported by merchant", impact: "₹499 returned; no settlement created", status: "Refund completed by Pine" } },
  { id: "ord_HDFC_104", partnerId: "hdfc", merchant: "Kaveri Textiles", contactName: "Meera Nair", email: "meera@kaveritextiles.in", gstin: "29AACCK7711B1Z4", consentAt: "23 Sep 2026, 5:12 PM", offer: "POS + Business Line", placed: "Yesterday", status: "Installation scheduled", settlement: "Held", amount: "₹4,999", endpoint: "https://api.hdfcbank.com/pine/bundle", deliveryResult: "23 Sep, 5:14 PM · 202 Accepted" },
];

export const initialInterests: Interest[] = [
  { id: "int-anjali", partnerId: "petpooja", business: "Anjali Sarees", contactName: "Anjali Reddy", phone: "+91 98••••••32", email: "anjali@anjalisarees.in", taxId: "07AAACR•••••1Z8", city: "Chennai · MG Road", category: "Retail · Apparel", offer: "Inventory Software — Diwali", capturedAt: "Today, 10:10 PM", capturedOrder: 4, consentShared: true, status: "Interest captured", answers: [{ question: "Monthly turnover", answer: "₹5L–₹25L" }, { question: "How soon are you looking to adopt?", answer: "Within 30 days" }], note: "" },
  { id: "int-meenakshi", partnerId: "petpooja", business: "Meenakshi Stores", contactName: "Priya Menon", phone: "+91 97••••••18", email: "priya@meenakshistores.in", taxId: "07AACCM•••••1Z3", city: "Delhi · Barakhamba", category: "Retail · General", offer: "PetPooja CRM — First Year", capturedAt: "Today, 7:45 PM", capturedOrder: 3, consentShared: true, status: "Contacted", answers: [{ question: "Monthly turnover", answer: "₹25L–₹1Cr" }, { question: "How soon are you looking to adopt?", answer: "Immediately" }], note: "Demo scheduled for Friday." },
  { id: "int-anonymous", partnerId: "petpooja", business: "Merchant · consent not shared", contactName: "Hidden", phone: "Hidden", email: "Hidden", taxId: "Hidden", city: "Pune", category: "Retail", offer: "PetPooja CRM — First Year", capturedAt: "Today, 5:20 PM", capturedOrder: 2, consentShared: false, status: "Interest captured", answers: [{ question: "Monthly turnover", answer: "Not shared" }], note: "" },
  { id: "int-hdfc", partnerId: "hdfc", business: "Shree Balaji Foods", contactName: "Rohan Gupta", phone: "+91 99••••••52", email: "rohan@balajifoods.in", taxId: "27AACCS•••••1Z7", city: "Mumbai · Andheri", category: "Food & beverage", offer: "HDFC Business Line", capturedAt: "Yesterday, 4:30 PM", capturedOrder: 1, consentShared: true, status: "Interest captured", answers: [{ question: "Requested credit amount", answer: "₹8,00,000" }, { question: "Primary use of funds", answer: "Expansion" }], note: "" },
];

export function cloneInitialDrafts(): DraftStore {
  return structuredClone(initialDrafts);
}
