import type { DraftStore, Engagement, OfferRecord, OfferType, PartnerId, PartnerProfile, PaymentAttempt } from "./types";

export const partnerProfiles: Record<PartnerId, PartnerProfile> = {
  petpooja: {
    id: "petpooja",
    name: "PetPooja",
    legalName: "PetPooja Pvt Ltd",
    role: "Admin",
    initials: "P",
    availableOfferTypes: ["direct-buy", "lead-gen"],
  },
  hdfc: {
    id: "hdfc",
    name: "HDFC Bank",
    legalName: "HDFC Bank Limited",
    role: "Partnerships",
    initials: "H",
    availableOfferTypes: ["financial", "linked"],
  },
};

export const offerTypeMeta: Record<OfferType, { title: string; eyebrow: string; description: string; goodFor: string }> = {
  "lead-gen": { title: "Lead generation", eyebrow: "No payment", description: "Merchant fills a form, you follow up offline.", goodFor: "Trials, demos and assisted subscriptions" },
  "direct-buy": { title: "Direct Buy", eyebrow: "Pay via Pine", description: "Merchant pays via Pine, you deliver.", goodFor: "Software licences, hardware and SaaS" },
  financial: { title: "Financial application", eyebrow: "Bank / NBFC", description: "Merchant applies, your team runs KYC and decides.", goodFor: "Loans, cards, accounts and insurance" },
  linked: { title: "Linked bundle", eyebrow: "Bank only", description: "One application covers an account and a device.", goodFor: "Account + POS and multi-leg products" },
};

const common = {
  productMark: "",
  productMarkUrl: "",
  fulfilmentMode: "partner-managed" as const,
  regulatedEntity: "",
  licence: "",
  cin: "",
  productFamily: "",
  interestRange: "",
  creditCeiling: "",
  disclosures: "",
  dpdpConsent: false,
  mitcFile: "",
  mitcUrl: "",
  complianceSignoff: false,
  postTrialPrice: "",
  contactSla: "",
  deviceSku: "",
  devicePrice: "",
  inventory: "",
  deviceFulfilment: "",
  heroCreativeUrl: "",
};

export const initialDrafts: DraftStore = {
  petpooja: {
    "direct-buy": {
      ...common,
      id: "draft-pet-direct",
      partnerId: "petpooja",
      type: "direct-buy",
      offerName: "Petpooja POS — Annual",
      category: "Billing & POS",
      headline: "1-year Restaurant POS subscription",
      benefit: "Billing, KOT, inventory, analytics — all in one",
      productDescription: "Full-stack restaurant management for growing food businesses.",
      sku: "PP-POS-ANN-2026",
      price: "9999",
      fulfilment: "Digital · SaaS subscription (1 year)",
      fulfilmentMode: "instant",
      heroCreative: "petpooja_hero_1440x810.png",
      validFrom: "2026-10-01",
      validUntil: "2027-09-30",
      terms: "Annual subscription includes onboarding, software updates and standard support. Cancellation and refund terms apply as per the partner policy.",
      questions: [],
    },
    "lead-gen": {
      ...common,
      id: "draft-pet-lead",
      partnerId: "petpooja",
      type: "lead-gen",
      offerName: "3-month free trial · Restaurant POS",
      category: "Billing & POS",
      headline: "3 months free · Restaurant POS software",
      benefit: "Full features · No card required · Cancel anytime",
      productDescription: "Full-stack restaurant management: billing, KOT, inventory, aggregator integrations and GST-ready reports.",
      sku: "PP-POS-TRIAL-2026",
      price: "",
      fulfilment: "Partner follow-up",
      postTrialPrice: "₹1,299/mo",
      contactSla: "48",
      heroCreative: "petpooja_trial_1440x810.png",
      validFrom: "2026-09-15",
      validUntil: "2026-12-15",
      terms: "Trial terms, cancellation policy and data-handling commitments apply.",
      questions: [
        { id: "q-turnover", label: "Monthly turnover", type: "single-select", required: false, options: ["Below ₹5L", "₹5L–₹25L", "₹25L–₹1Cr", "Above ₹1Cr"] },
        { id: "q-timing", label: "How soon are you looking to adopt?", type: "single-select", required: true, options: ["Immediately", "Within 30 days", "Just exploring"] },
      ],
    },
  },
  hdfc: {
    financial: {
      ...common,
      id: "draft-hdfc-financial",
      partnerId: "hdfc",
      type: "financial",
      offerName: "HDFC Business Line — Pre-approved",
      category: "Financial services · Credit",
      headline: "Pre-approved business loan up to ₹15L",
      benefit: "Interest from 12% p.a. · Decision in 24–72 hrs",
      productDescription: "A flexible business line of credit for working capital and growth.",
      sku: "HDFC-BIZLINE-PRE",
      price: "",
      fulfilment: "Application · HDFC underwriting",
      regulatedEntity: "HDFC Bank Limited",
      licence: "RBI licence · Scheduled commercial bank",
      cin: "L65920MH1994PLC080618",
      productFamily: "Business line of credit",
      interestRange: "12% – 18%",
      creditCeiling: "1500000",
      disclosures: "APR, processing fee, penalty on default, cooling-off period and grievance officer contact.",
      dpdpConsent: true,
      mitcFile: "hdfc_business_line_mitc.pdf",
      complianceSignoff: true,
      heroCreative: "hdfc_bizloan_1440x810.png",
      validFrom: "2026-10-01",
      validUntil: "2027-03-31",
      terms: "Platform terms, DPDP consent and the HDFC Bank MITC apply.",
      questions: [
        { id: "q-amount", label: "Requested credit amount", type: "short-text", required: true, options: [] },
        { id: "q-use", label: "Primary use of funds", type: "single-select", required: true, options: ["Working capital", "Equipment", "Expansion", "Other"] },
      ],
    },
    linked: {
      ...common,
      id: "draft-hdfc-linked",
      partnerId: "hdfc",
      type: "linked",
      offerName: "POS terminal + HDFC Business Line",
      category: "Hardware · Financial services",
      headline: "Get a POS terminal + credit line up to ₹10L",
      benefit: "One commitment · device + credit line",
      productDescription: "A Pine POS terminal bundled with an HDFC Business Line application.",
      sku: "HDFC-BUNDLE-2026",
      price: "4999",
      fulfilment: "Two-leg bundle",
      regulatedEntity: "HDFC Bank Limited",
      licence: "RBI licence · Scheduled commercial bank",
      cin: "L65920MH1994PLC080618",
      productFamily: "HDFC Business Line",
      interestRange: "12% – 18%",
      creditCeiling: "1000000",
      disclosures: "APR, processing fee, penalty, cooling-off period and grievance contact.",
      dpdpConsent: true,
      mitcFile: "hdfc_bundle_mitc.pdf",
      complianceSignoff: true,
      deviceSku: "POS-NKD-2P-STD",
      devicePrice: "4999",
      inventory: "1200",
      deviceFulfilment: "Physical · 3–5 days",
      heroCreative: "hdfc_pos_bundle_1440x810.png",
      validFrom: "2026-10-01",
      validUntil: "2027-03-31",
      terms: "Platform, order, bundle, DPDP consent and HDFC Bank product terms apply.",
      questions: [
        { id: "q-city", label: "Preferred installation city", type: "short-text", required: true, options: [] },
        { id: "q-purpose", label: "Primary credit-line use", type: "single-select", required: true, options: ["Working capital", "Expansion", "Inventory", "Other"] },
      ],
    },
  },
};

export const initialOffers: OfferRecord[] = [
  { id: "offer-rejected", campaignId: "CMP-2026-1042", partnerId: "petpooja", draftType: "lead-gen", name: "Inventory Software — Diwali", meta: "T&Cs missing redemption cap", typeLabel: "Lead-gen", category: "Inventory management", deal: "₹2,000 off annual", performance: { kind: "lead", leadCount: 8, convertedCount: 0 }, engagedCount: 8, convertedCount: 0, status: "Rejected", validFrom: "2026-10-01", validUntil: "2026-11-15", attentionPriority: 1, attentionLabel: "Rejected · correction required" },
  { id: "offer-live", campaignId: "CMP-2026-1018", partnerId: "petpooja", draftType: "lead-gen", name: "PetPooja CRM — First Year", meta: "Ends in 2 days · 18 open leads", typeLabel: "Lead-gen", category: "Loyalty & CRM", deal: "First year 50% off", performance: { kind: "lead", leadCount: 30, convertedCount: 20 }, engagedCount: 30, convertedCount: 20, status: "Live", validFrom: "2026-07-01", validUntil: "2026-10-01", attentionPriority: 3, attentionLabel: "Ends in 2 days · 18 open leads" },
  { id: "offer-review", campaignId: "CMP-2026-1048", partnerId: "petpooja", draftType: "lead-gen", name: "GST Filing Bundle", meta: "Under review 52 hrs · longer than usual", typeLabel: "Lead-gen", category: "Compliance & accounting", deal: "Bundle + support", performance: { kind: "lead", leadCount: 0, convertedCount: 0 }, engagedCount: 0, convertedCount: 0, status: "Under review", validFrom: "2026-10-15", validUntil: "2027-03-31", attentionPriority: 2, attentionLabel: "Review SLA breached · Pine notified" },
  { id: "offer-paused", campaignId: "CMP-2026-0987", partnerId: "petpooja", draftType: "direct-buy", name: "Restaurant POS", meta: "Paused 07 Sep", typeLabel: "Direct Buy", category: "Billing & POS", deal: "Free setup + 3 months", performance: { kind: "direct-buy", purchaseCount: 9, revenue: "₹89,991" }, engagedCount: 9, convertedCount: 0, status: "Paused", validFrom: "2026-08-20", validUntil: "2027-03-31", revenue: "₹89,991", attentionPriority: 5 },
  { id: "offer-ended", campaignId: "CMP-2026-0921", partnerId: "petpooja", draftType: "direct-buy", name: "Kitchen Display System", meta: "Ended 31 Aug", typeLabel: "Direct Buy", category: "Billing & POS", deal: "Bundle discount", performance: { kind: "direct-buy", purchaseCount: 62, revenue: "₹3,09,938" }, engagedCount: 62, convertedCount: 0, status: "Ended", validFrom: "2026-04-01", validUntil: "2026-08-31", revenue: "₹3,09,938", attentionPriority: 6 },
  { id: "hdfc-fin-live", campaignId: "CMP-2026-1004", partnerId: "hdfc", draftType: "financial", name: "HDFC Business Line", meta: "Live since 03 Sep", typeLabel: "Financial application", category: "Financial services · Credit", deal: "Credit line up to ₹15L", performance: { kind: "application", applicationCount: 84, approvedCount: 26 }, engagedCount: 84, convertedCount: 26, status: "Live", validFrom: "2026-09-03", validUntil: "2027-03-31", attentionPriority: 4 },
  { id: "hdfc-linked-review", campaignId: "CMP-2026-1051", partnerId: "hdfc", draftType: "linked", name: "POS + Business Line", meta: "Submitted yesterday", typeLabel: "Linked bundle", category: "Hardware · Financial services", deal: "Device + credit line", performance: { kind: "application", applicationCount: 18, approvedCount: 6 }, engagedCount: 18, convertedCount: 6, status: "Under review", validFrom: "2026-10-10", validUntil: "2027-03-31", attentionPriority: 4 },
];

export const initialPaymentAttempts: PaymentAttempt[] = [
  { id: "PAY-2026-2142", orderId: "ORD-2026-1042", offerId: "offer-paused", partnerId: "petpooja", merchant: "Cafe Mocha Andheri", contactName: "Rahul Shah", email: "rahul@cafemocha.in", gstin: "27AABCU9603R1ZM", consentAt: "24 Sep 2026, 11:02 AM", offer: "Restaurant POS", eventAt: "2 hrs ago", paymentStatus: "successful", fulfilmentMode: "partner-managed", amount: "₹9,999", paymentReference: "PG-884210", dataSharedAt: "24 Sep 2026, 11:03 AM" },
  { id: "PAY-2026-2141", orderId: "ORD-2026-1041", offerId: "offer-paused", partnerId: "petpooja", merchant: "Momo Point Koramangala", contactName: "Maya Rao", email: "maya@momopoint.in", gstin: "29AACCM4422P1Z8", consentAt: "24 Sep 2026, 7:28 AM", offer: "Restaurant POS", eventAt: "6 hrs ago", paymentStatus: "successful", fulfilmentMode: "instant", amount: "₹9,999", paymentReference: "PG-884117", dataSharedAt: "24 Sep 2026, 7:30 AM" },
  { id: "PAY-2026-2140", offerId: "offer-paused", partnerId: "petpooja", merchant: "Anand Bhavan", contactName: "Karthik Iyer", email: "karthik@anandbhavan.in", gstin: "33AAECA1102D1ZP", consentAt: "23 Sep 2026, 2:10 PM", offer: "Restaurant POS", eventAt: "Yesterday", paymentStatus: "failed", fulfilmentMode: "instant", amount: "₹9,999", paymentReference: "PG-883984" },
  { id: "PAY-2026-2139", offerId: "offer-ended", partnerId: "petpooja", merchant: "Delhi Darbar", contactName: "Fahad Khan", email: "fahad@delhidarbar.in", gstin: "07AAHFD2204N1Z5", consentAt: "22 Sep 2026, 10:15 AM", offer: "Kitchen Display System", eventAt: "2 days ago", paymentStatus: "abandoned", fulfilmentMode: "partner-managed", amount: "₹499" },
  { id: "PAY-2026-2138", orderId: "ORD-2026-1038", offerId: "offer-ended", partnerId: "petpooja", merchant: "Spice Route", contactName: "Nisha Patel", email: "nisha@spiceroute.in", gstin: "27AACCS1104N1Z5", consentAt: "21 Sep 2026, 4:15 PM", offer: "Kitchen Display System", eventAt: "3 days ago", paymentStatus: "refunded", fulfilmentMode: "partner-managed", amount: "₹4,999", paymentReference: "PG-883712", dataSharedAt: "21 Sep 2026, 4:16 PM", refund: { confirmedAt: "23 Sep 2026, 9:40 AM", amount: "₹4,999", reference: "RF-2026-0451" } },
  { id: "PAY-2026-2204", offerId: "hdfc-linked-review", bundleId: "BND-2026-0204", partnerId: "hdfc", merchant: "Kaveri Textiles", contactName: "Meera Nair", email: "meera@kaveritextiles.in", gstin: "29AACCK7711B1Z4", consentAt: "23 Sep 2026, 5:12 PM", offer: "POS + Business Line", eventAt: "Yesterday", paymentStatus: "authorised", fulfilmentMode: "partner-managed", amount: "₹4,999", paymentReference: "PG-AUTH-9014" },
];

export const initialEngagements: Engagement[] = [
  { kind: "lead", id: "LEAD-2026-1142", partnerId: "petpooja", offerId: "offer-rejected", offer: "Inventory Software — Diwali", business: "Anjali Sarees", submittedAt: "Today, 10:10 PM", submittedOrder: 6, slaStatus: "due-soon", slaLabel: "6 hrs left", consentShared: true, contactName: "Anjali Reddy", phone: "+91 98••••••32", email: "anjali@anjalisarees.in", taxId: "07AAACR•••••1Z8", city: "Chennai · MG Road", category: "Retail · Apparel", state: "SUBMITTED", answers: [{ question: "Monthly turnover", answer: "₹5L–₹25L" }, { question: "How soon are you looking to adopt?", answer: "Within 30 days" }], note: "", history: [{ label: "Lead submitted", at: "Today, 10:10 PM", detail: "Merchant shared contact details and consent." }] },
  { kind: "lead", id: "LEAD-2026-1138", partnerId: "petpooja", offerId: "offer-live", offer: "PetPooja CRM — First Year", business: "Meenakshi Stores", submittedAt: "Today, 7:45 PM", submittedOrder: 5, slaStatus: "healthy", slaLabel: "31 hrs left", consentShared: true, contactName: "Priya Menon", phone: "+91 97••••••18", email: "priya@meenakshistores.in", taxId: "07AACCM•••••1Z3", city: "Delhi · Barakhamba", category: "Retail · General", state: "CONTACTED", answers: [{ question: "Monthly turnover", answer: "₹25L–₹1Cr" }, { question: "How soon are you looking to adopt?", answer: "Immediately" }], note: "Demo scheduled for Friday.", history: [{ label: "Lead submitted", at: "Today, 7:45 PM", detail: "Merchant shared contact details and consent." }, { label: "Marked contacted", at: "Today, 8:20 PM", detail: "PetPooja confirmed first contact." }] },
  { kind: "lead", id: "LEAD-2026-1132", partnerId: "petpooja", offerId: "offer-live", offer: "PetPooja CRM — First Year", business: "Anonymous", submittedAt: "Today, 5:20 PM", submittedOrder: 4, slaStatus: "healthy", slaLabel: "Consent pending", consentShared: false, contactName: "", phone: "", email: "", taxId: "", city: "Pune", category: "Retail", state: "SUBMITTED", answers: [{ question: "Monthly turnover", answer: "Not shared" }], note: "", history: [{ label: "Anonymous interest submitted", at: "Today, 5:20 PM", detail: "Contact details were not shared." }] },
  { kind: "lead", id: "LEAD-2026-1097", partnerId: "petpooja", offerId: "offer-live", offer: "PetPooja CRM — First Year", business: "Cafe Juniper", submittedAt: "27 Sep, 3:15 PM", submittedOrder: 3, slaStatus: "breached", slaLabel: "SLA breached by 18 hrs", consentShared: true, contactName: "Rhea Kapoor", phone: "+91 96••••••41", email: "rhea@cafejuniper.in", taxId: "29AACCC•••••1Z2", city: "Bengaluru · Indiranagar", category: "Food & beverage", state: "SUBMITTED", answers: [{ question: "How soon are you looking to adopt?", answer: "Immediately" }], note: "", history: [{ label: "Lead submitted", at: "27 Sep, 3:15 PM", detail: "Merchant shared contact details and consent." }, { label: "SLA breached", at: "Today, 9:15 AM", detail: "Pine was notified; manual follow-up required." }] },
  { kind: "application", id: "APP-2026-0821", partnerId: "hdfc", offerId: "hdfc-fin-live", offer: "HDFC Business Line", business: "Shree Balaji Foods", submittedAt: "Yesterday, 4:30 PM", submittedOrder: 3, slaStatus: "due-soon", slaLabel: "9 hrs left", consentShared: true, contactName: "Rohan Gupta", phone: "+91 99••••••52", email: "rohan@balajifoods.in", taxId: "27AACCS•••••1Z7", city: "Mumbai · Andheri", category: "Food & beverage", state: "UNDER_REVIEW", regulatedEntity: "HDFC Bank Limited", answers: [{ question: "Requested credit amount", answer: "₹8,00,000" }, { question: "Primary use of funds", answer: "Expansion" }], note: "KYC documents received through the bank integration.", history: [{ label: "Application submitted", at: "Yesterday, 4:30 PM", detail: "Consent and application data shared with HDFC Bank Limited." }, { label: "Under review", at: "Today, 9:10 AM", detail: "State supplied by the bank integration." }] },
  { kind: "application", id: "APP-2026-0814", partnerId: "hdfc", offerId: "hdfc-linked-review", offer: "POS + Business Line", business: "Kaveri Textiles", submittedAt: "23 Sep, 5:12 PM", submittedOrder: 2, slaStatus: "breached", slaLabel: "SLA breached by 28 hrs", consentShared: true, contactName: "Meera Nair", phone: "+91 98••••••76", email: "meera@kaveritextiles.in", taxId: "29AACCK•••••1Z4", city: "Bengaluru · Chickpet", category: "Retail · Apparel", state: "INFO_NEEDED", regulatedEntity: "HDFC Bank Limited", bundleId: "BND-2026-0204", paymentAttemptId: "PAY-2026-2204", answers: [{ question: "Requested credit amount", answer: "₹6,00,000" }, { question: "Primary use of funds", answer: "Inventory" }], note: "Bank requested the latest GST return.", history: [{ label: "Application submitted", at: "23 Sep, 5:12 PM", detail: "Part of bundle BND-2026-0204." }, { label: "More information needed", at: "25 Sep, 11:30 AM", detail: "State supplied by the bank integration." }, { label: "SLA breached", at: "Today, 11:30 AM", detail: "Pine was notified for manual follow-up." }] },
];

export function cloneInitialDrafts(): DraftStore {
  return structuredClone(initialDrafts);
}
